alpha_learning_rate: 0.0003
buffer_size: 2000000
batch_size: 256
env_name: "halfcheetah-medium-expert-v2"
actor_learning_rate: 0.0003
critic_learning_rate: 0.0003
checkpoints_path: null
device: cuda
num_updates_on_epoch: 1000
eval_every: 5
eta: 5.0
eval_seed: 42
eval_episodes: 10
group: "edac-halfcheetah-medium-expert-v2-multiseed-v2"
gamma: 0.99
log_every: 100
max_action: 1.0
num_critics: 10
hidden_dim: 256
num_epochs: 3000
name: "EDAC"
project: "offline_rl"
tau: 0.005
train_seed: 10